export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const RESTAURANT_FETCHED = 'RESTAURANT_FETCHED';
export const RESTAURANT_CREATED = 'RESTAURANT_CREATED';